"""membuat table iventory

Revision ID: 796c7c22cb35
Revises: 2b5253b1478f
Create Date: 2024-10-23 13:36:58.683630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796c7c22cb35'
down_revision = '2b5253b1478f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iventory',
    sa.Column('id_iventory', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_barang', sa.String(length=200), nullable=False),
    sa.Column('jumlah_barang', sa.Integer(), nullable=True),
    sa.Column('kondisi_barang', sa.String(length=200), nullable=False),
    sa.Column('jumlah_barang_rusak', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_iventory')
    )
    with op.batch_alter_table('iventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iventory_nama_barang'), ['nama_barang'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iventory_nama_barang'))

    op.drop_table('iventory')
    # ### end Alembic commands ###
